export enum APIErrors {
    INVALID_EMAIL_OR_PASSWORD = "AUTH_WRONG_PASSWORD",
    AUTH_INVALID_EMAIL = "AUTH_INVALID_EMAIL",
    AUTH_EMAIL_ALREADY_IN_USE = "AUTH_EMAIL_ALREADY_IN_USE",
    AUTH_WEAK_PASSWORD = "AUTH_WEAK_PASSWORD",
    UNKNOWN_ERROR_HAS_OCCURRED = "UNKNOWN_ERROR_HAS_OCCURRED",
}
